// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysFsFileDao is the data access object for the table sys_fs_file.
// You can define custom methods on it to extend its functionality as needed.
type sysFsFileDao struct {
	*internal.SysFsFileDao
}

var (
	// SysFsFile is a globally accessible object for table sys_fs_file operations.
	SysFsFile = sysFsFileDao{internal.NewSysFsFileDao()}
)

// Add your custom methods and functionality below.
