// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysComplaintLogsDao is the data access object for the table sys_complaint_logs.
// You can define custom methods on it to extend its functionality as needed.
type sysComplaintLogsDao struct {
	*internal.SysComplaintLogsDao
}

var (
	// SysComplaintLogs is a globally accessible object for table sys_complaint_logs operations.
	SysComplaintLogs = sysComplaintLogsDao{internal.NewSysComplaintLogsDao()}
)

// Add your custom methods and functionality below.
