// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysComplaintFeedbackDao is the data access object for the table sys_complaint_feedback.
// You can define custom methods on it to extend its functionality as needed.
type sysComplaintFeedbackDao struct {
	*internal.SysComplaintFeedbackDao
}

var (
	// SysComplaintFeedback is a globally accessible object for table sys_complaint_feedback operations.
	SysComplaintFeedback = sysComplaintFeedbackDao{internal.NewSysComplaintFeedbackDao()}
)

// Add your custom methods and functionality below.
