// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysFsDirDao is the data access object for the table sys_fs_dir.
// You can define custom methods on it to extend its functionality as needed.
type sysFsDirDao struct {
	*internal.SysFsDirDao
}

var (
	// SysFsDir is a globally accessible object for table sys_fs_dir operations.
	SysFsDir = sysFsDirDao{internal.NewSysFsDirDao()}
)

// Add your custom methods and functionality below.
