// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysComplaintsDao is the data access object for the table sys_complaints.
// You can define custom methods on it to extend its functionality as needed.
type sysComplaintsDao struct {
	*internal.SysComplaintsDao
}

var (
	// SysComplaints is a globally accessible object for table sys_complaints operations.
	SysComplaints = sysComplaintsDao{internal.NewSysComplaintsDao()}
)

// Add your custom methods and functionality below.
